### ISSUE TITLE
Ticking Entity Server Crash

### ISSUE THREAD

**Issue by Giggitybyte** [mujmajnkraft/BetterSurvival#2]
I originally thought the crashes were caused by Lycanites Mobs. However, the dev of Lycanites Mobs told me the crashes were caused by Better Survival and triggered by Lycanites Mobs (see Lycanite/LycanitesMobs#245). To get around whatever is causing this, I've enabled both `removeErroringEntities` and `removeErroringTileEntities` in forge.cfg, but I don't want to rely on those and would prefer to have them off. I hope you can look into this and fix it :)

Here are a few of the crash logs I've gotten:
https://hastebin.com/ohanayofok.txt
https://hastebin.com/ocehadorec.txt
https://hastebin.com/ehozigiwuy.txt

**Comment by mujmajnkraft** [comment]
I think it should be fixed in the newest version (1.3.3)

**Comment by AetherBreaker** [comment]
I would like to say in the current version of the mod this issue is most certainly not fixed, using version 1.4.1 and have encountered this issue on two separate occasions
